fitness_world/profiles/urls.py
from django.urls import path, include
from fitness_world.profiles import views

urlpatterns = [
    path('login/', views.SignInView.as_view(), name='sign in'),
    path('register/', views.SignUpView.as_view(), name='sign up'),
    path('logout/', views.SignOutView.as_view(), name='sign out'),
    path('profile/', include([
        path('details/<int:pk>/', views.DetailsUserView.as_view(), name='details user'),
        path('edit/<int:pk>/', views.EditUserView.as_view(), name='edit user'),
        path('delete/<int:pk>/', views.DeleteUserView.as_view(), name='delete user'),
    ]))
]

fitness_world/urls.py
from django.conf.urls.static import static

from fitness_world import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitness_world.common.urls')),
    path('photo/', include('fitness_world.photos.urls')),
    path('', include('fitness_world.profiles.urls')),
    path('workout/', include('fitness_world.workouts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fitness_world/profiles/models.py
from django.contrib.auth import models as auth_models
from django.core import validators
from django.db import models

from fitness_world.core.mixins import ChoicesMixin


# Create your models here.

class Gender(ChoicesMixin):
    Male = 'Male'
    Female = 'Female'


class AppUser(auth_models.AbstractUser):
    MAX_LEN_NAMES = 20
    MIN_LEN_NAMES = 2

    first_name = models.CharField(
        max_length=MAX_LEN_NAMES,
        null=True,
        blank=True,
        validators=(
            validators.MinLengthValidator(MIN_LEN_NAMES, ),
        ),
        error_messages={
            "min_length": f'First name must be grater than {MIN_LEN_NAMES} characters'
        }
    )

    last_name = models.CharField(
        max_length=MAX_LEN_NAMES,
        null=True,
        blank=True,
        validators=(
            validators.MinLengthValidator(MIN_LEN_NAMES, ),
        ),
        error_messages={
            "min_length": f'Last name must be grater than {MIN_LEN_NAMES} characters'
        }
    )

    email = models.EmailField(
        unique=True,
    )

    profile_picture = models.URLField(
        null=True,
        blank=True,
    )

    gender = models.CharField(
        max_length=Gender.max_len(),
        choices=Gender.choices(),
        null=True,
        blank=True,
    )

    weight = models.PositiveIntegerField(
        null=True,
        blank=True,
    )

fitness_world/workouts/models.py
from django.contrib.auth import get_user_model
from django.core import validators
from django.db import models
from django.utils.text import slugify


UserModel = get_user_model()


class Workout(models.Model):
    MAX_LEN_NAME = 40
    MIN_LEN_NAME = 3

    class Meta:
        ordering = ('-pk',)

    name = models.CharField(
        null=False,
        blank=False,
        max_length=MAX_LEN_NAME,
        validators=(
            validators.MinLengthValidator(MIN_LEN_NAME,),
        ),
    )

    reps = models.PositiveIntegerField(
        null=False,
        blank=False,
    )

    sets = models.PositiveIntegerField(
        null=False,
        blank=False,
    )

    slug = models.SlugField(
        unique=True,
        null=False,
        blank=True,
    )

    link_to_image = models.URLField(
        max_length=500,
        null=False,
        blank=False,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        self.slug = slugify(self.name)

        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

fitness_world/profiles/forms.py
from django.contrib.auth import forms as auth_forms, get_user_model, password_validation
from django import forms
from django.contrib.auth.forms import UsernameField


UserModel = get_user_model()


class SignInForm(auth_forms.AuthenticationForm):
    username = auth_forms.UsernameField(
        widget=forms.TextInput(
            attrs={
                "autofocus": True,
                'placeholder': 'Username'
            }
        )
    )

    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "current-password",
                'placeholder': 'Password',
            }
        ),
    )


class UserCreateForm(auth_forms.UserCreationForm):
    password1 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'placeholder': 'Password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'placeholder': 'Repeat Password'}),
        strip=False,
        help_text="Enter the same password as before, for verification.",
    )

    class Meta:
        model = UserModel
        fields = ("username", 'email', 'password1', 'password2',)
        field_classes = {"username": auth_forms.UsernameField}

        widgets = {
            'username': forms.TextInput(
                attrs={
                    'placeholder': 'Username',
                }
            ),

            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Email',
                }
            )
        }


class UserEditForm(auth_forms.UserChangeForm):
    class Meta:
        model = UserModel
        fields = "__all__"
        field_classes = {"username": UsernameField}

fitness_world/profiles/views.py
from django.contrib.auth import views as auth_views, get_user_model, login
from django.contrib.auth import mixins as auth_mixins
from django.shortcuts import redirect
from django.views import generic
from django.urls import reverse_lazy

from fitness_world import settings
from fitness_world.common.views import page_not_found
from fitness_world.core.core_utils import user_permissions
from fitness_world.core.photo_utils import photo_likes_count
from fitness_world.core.user_utils import likes_for_photos_delete, comments_for_photos_delete, workouts_delete
from fitness_world.photos.models import Photo
from fitness_world.profiles.forms import SignInForm, UserCreateForm
from fitness_world.workouts.models import Workout

UserModel = get_user_model()


class SignInView(auth_views.LoginView):
    form_class = SignInForm
    template_name = 'profiles/login-page.html'


class SignUpView(generic.CreateView):
    template_name = 'profiles/register-page.html'
    form_class = UserCreateForm
    success_url = reverse_lazy('index')

    # After register user, doesn't need to log in to access the site!
    def form_valid(self, form):
        result = super().form_valid(form)

        login(self.request, self.object)
        return result


class SignOutView(auth_mixins.LoginRequiredMixin, auth_views.LogoutView):
    next_page = reverse_lazy('index')


class DeleteUserView(auth_mixins.LoginRequiredMixin, auth_mixins.UserPassesTestMixin, generic.DeleteView):
    template_name = 'profiles/profile-delete-page.html'
    model = UserModel
    success_url = reverse_lazy('index')

    def test_func(self):
        try:
            user_pk = self.kwargs.get('pk')
            owner = UserModel.objects.filter(pk=user_pk).get()
            return user_permissions(self.request, owner)
        except UserModel.DoesNotExist:
            page_not_found(self.request)

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return redirect(settings.LOGIN_URL)

        return page_not_found(self.request)

    def form_valid(self, form):
        success_url = self.get_success_url()

        owned_photos = Photo.objects.filter(user_id=self.object.pk).all()

        workouts_delete(user=self.object)
        likes_for_photos_delete(owned_photos, self.object)
        comments_for_photos_delete(owned_photos, self.object)
        owned_photos.delete()

        self.object.delete()
        return redirect(success_url)


class DetailsUserView(auth_mixins.LoginRequiredMixin, generic.DetailView):
    template_name = 'profiles/profile-details-page.html'
    model = UserModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        owned_photos = Photo.objects.filter(user_id=self.object.pk).all()

        context['is_owner'] = self.request.user == self.object
        context['have_full_name'] = self.object.first_name and self.object.last_name
        context['total_photos_owned'] = owned_photos
        context['total_workouts_owned'] = Workout.objects.filter(user_id=self.object.pk).count()
        context['ordered_photos'] = owned_photos.order_by('-date_of_publication')

        owned_photos = [photo_likes_count(photo) for photo in owned_photos]
        context['total_likes'] = sum(p.likes for p in owned_photos)

        return context


class EditUserView(auth_mixins.LoginRequiredMixin, auth_mixins.UserPassesTestMixin, generic.UpdateView):
    template_name = 'profiles/profile-edit-page.html'
    model = UserModel
    fields = ('username', 'email', 'first_name', 'last_name', 'profile_picture', 'weight', 'gender')

    def test_func(self):
        try:
            user_pk = self.kwargs.get('pk')
            owner = UserModel.objects.filter(pk=user_pk).get()
            return user_permissions(self.request, owner)
        except UserModel.DoesNotExist:
            page_not_found(self.request)

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return redirect(settings.LOGIN_URL)

        return page_not_found(self.request)

    def get_success_url(self):
        return reverse_lazy('details user', kwargs={
            'pk': self.object.pk,
        })

templates/profiles/login-page.html
{% extends 'base/base.html' %}

{% block content %}
<main>

    <div class="login-register-div">
        <div class="login-register-box">
            <h1>FitnessWorld</h1>

            <form method="post" action="{% url 'sign in' %}">
                {{ form }}
                {% csrf_token %}
                <button type="submit">Log in</button>
            </form>

        </div>
        <div class="second-option">

            <p>Don't have account? <a href="{% url 'sign up' %}">Register</a></p>
        </div>
    </div>

</main>

{% endblock content %}

templates/profiles/profile-delete-page.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<main>

        <div class="delete-profile">
            <h1>
                Are you sure you want to delete your profile?
            </h1>
            <div class="sure-buttons">
                <form method="post" action="{% url 'delete user' pk=object.pk %}">
                    {% csrf_token %}
                    <button>Yes</button>
                </form>

                <a class="edit-btn" href="javascript:history.back()">Go Back</a>
            </div>
        </div>

</main>


{% endblock content %}

templates/profiles/profile-details-page.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <main>

        <div class="profile">

            <div class="profile-data">
                <div class="profile_img">
                    <div class="image">
                        {% if not object.profile_picture %}
                            <img src="{% static 'images/person.png' %}" alt="img8">
                        {% else %}
                            <img src="{{ object.profile_picture }}" alt="img8">
                        {% endif %}
                    </div>
                </div>
                <div class="personal">
                    <div class="edit">
                        <p>{{ object.username }}</p>

                        {% if is_owner or request.user.is_superuser %}
                            <a href="{% url 'edit user' pk=object.pk %}">
                                <img class="edit-img" src="{% static 'images/edit-pen-icon-6.jpg' %}" alt="edit button">
                            </a>

                            <a href="{% url 'delete user' pk=object.pk %}">
                                <img class="bin-img" src="{% static 'images/icon-remove-22.jpg' %}" alt="bin button">
                            </a>
                        {% endif %}

                    </div>
                    <div class="data">

                        <span>{{ total_photos_owned.count }}</span>
                        <p>photos</p>

                        <span>{{ total_workouts_owned }}</span>
                        <p>workouts</p>

                        <span>{{ total_likes }}</span>
                        <p>likes</p>
                    </div>

                    {% if have_full_name %}
                        <h3 class="names">Full name: {{ object.get_full_name }}</h3>
                    {% endif %}

                    <p class="email">Email: {{ object.email }}</p>

                    {% if object.weight %}
                        <p class="weight">Weight: {{ object.weight }} kg</p>
                    {% endif %}

                    {% if object.gender %}
                        <p class="gender">Gender: {{ object.gender }}</p>
                    {% endif %}
                </div>
            </div>

            <div class="pets">
                <div class="statuses">

                    {% for workout in object.workout_set.all %}
                        <a href="{% url 'details workout' username=object.username slug=workout.slug %}">
                            <div class="head-pet">
                                <div class="status">
                                    <div class="image">

                                        <img src="{{ workout.link_to_image }}"
                                             alt="image-of-{{ workout.name }}">
                                    </div>
                                </div>
                                <p>{{ workout.name }}</p>
                            </div>
                        </a>
                    {% endfor %}

                </div>
            </div>

            {% if ordered_photos %}
                <div class="pet-photos">

                    {% for photo in ordered_photos %}
                        <a href="{% url 'details photo' pk=photo.pk %}">
                            <img src="/media/{{ photo.image }}"
                                 alt="photo-of-{{ photo.user.name }}">
                        </a>
                    {% endfor %}

                </div>
            {% else %}
                <div>
                    <img class="no-posts2" src="{% static 'images/no_posts.png' %}" alt="no posts image">
                </div>
            {% endif %}

        </div>

    </main>

{% endblock content %}

templates/profiles/profile-edit-page.html
{% extends 'base/base.html' %}

{% block content %}

    <main>
        <div class="edit-delete"><h2>Edit Profile</h2>
            <form method="post"> {% csrf_token %} {% for field in form %}<p class="error"> {{ field.errors }} </p>
                <div class="label-input"><label>{{ field.label }}</label> {% if not field.label == "Gender:" %}
                    {{ field }} {% else %}
                    <div class="list-choice">
                        <div class="list-choice-title">Gender</div>
                        <div class="list-choice-objects"> {% for type, value in form.fields.gender.choices %}
                            <label> <input type="radio" value="{{ value }}" name="gender"
                                    {% if form.gender.value == value %} checked {% endif %}/> <span>{{ value }}</span>
                            </label> {% endfor %} </div>
                    </div> {% endif %} </div> <br> {% endfor %}
                <button class="edit-btn" type="submit">Edit</button>
            </form>
        </div>

    </main>

{% endblock content %}

templates/profiles/register-page.html
{% extends 'base/base.html' %}

{% block content %}

    <main>

        <div class="login-register-div">
            <div class="login-register-box">
                <h1>FitnessWorld</h1>

                <form method="post" action="{% url 'sign up' %}">
                    {{ form.username.errors }}
                    {{ form.username }}
                    {{ form.email.errors }}
                    {{ form.email }}
                    {{ form.password1.errors }}
                    {{ form.password1 }}
                    {{ form.password2.errors }}
                    {{ form.password2 }}
                    {% csrf_token %}
                    <button type="submit">Register</button>
                </form>

            </div>
            <div class="second-option">

                <p>Have an account? <a href="{% url 'sign in' %}">Log in</a></p>
            </div>
        </div>

    </main>

{% endblock content %}