fitness_world/photos/urls.py
from django.urls import path
from fitness_world.photos import views

urlpatterns = [
    path('create/', views.CreatePhotoView.as_view(), name='create photo'),
    path('details/<int:pk>/', views.DetailsPhotoView.as_view(), name='details photo'),
    path('edit/<int:pk>/', views.EditPhotoView.as_view(), name='edit photo'),
    path('delete/<int:pk>/', views.delete_photo, name='delete photo'),
]

fitness_world/urls.py
from django.conf.urls.static import static

from fitness_world import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fitness_world.common.urls')),
    path('photo/', include('fitness_world.photos.urls')),
    path('', include('fitness_world.profiles.urls')),
    path('workout/', include('fitness_world.workouts.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fitness_world/common/models.py
from django.contrib.auth import get_user_model
from django.db import models

from fitness_world.photos.models import Photo

UserModel = get_user_model()


class LikePhoto(models.Model):
    photo = models.ForeignKey(
        Photo,
        on_delete=models.RESTRICT,
        null=False,
        blank=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )


class CommentPhoto(models.Model):
    class Meta:
        ordering = ('-publication_date',)

    MAX_TEXT_LENGTH = 200

    text = models.CharField(
        max_length=MAX_TEXT_LENGTH,
        null=False,
        blank=False,
    )

    publication_date = models.DateTimeField(
        auto_now_add=True,
    )

    photo = models.ForeignKey(
        Photo,
        on_delete=models.RESTRICT,
        null=False,
        blank=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )

    def __str__(self):
        return f"Comment {self.pk}: {self.text}"

fitness_world/photos/models.py
from django.contrib.auth import get_user_model
from django.core import validators
from django.db import models

from fitness_world.workouts.models import Workout


UserModel = get_user_model()


class Photo(models.Model):
    class Meta:
        ordering = ('-date_of_publication',)

    MAX_LEN_LOCATION = 30
    MIN_LEN_LOCATION = 3

    image = models.ImageField(
        upload_to='images/',
        null=False,
        blank=False,
    )

    location = models.CharField(
        max_length=MAX_LEN_LOCATION,
        validators=(
            validators.MinLengthValidator(MIN_LEN_LOCATION,),
        ),
        null=True,
        blank=True,
    )

    caption = models.TextField(
        null=True,
        blank=True,
    )

    music_link = models.URLField(
        null=True,
        blank=True,
    )

    workout = models.ManyToManyField(
        Workout,
        blank=True,
    )

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )

    date_of_publication = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return f"{self.image}"

fitness_world/photos/forms.py
from django import forms
from django.contrib.auth import get_user_model

from fitness_world.common.models import LikePhoto, CommentPhoto
from fitness_world.core.mixins import FieldsMixin
from fitness_world.photos.models import Photo

UserModel = get_user_model()


class PhotoBaseForm(forms.ModelForm):
    class Meta:
        model = Photo
        exclude = ('user', 'date_of_publication',)

        labels = {
            'music_link': 'Music Link',
            'workout': 'Workout Type',
        }

        widgets = {
            'location': forms.TextInput(
                attrs={
                    'placeholder': 'Location'
                }
            ),

            'caption': forms.Textarea(
                attrs={
                    'placeholder': 'Caption',
                }
            ),

            'music_link': forms.URLInput(
                attrs={
                    'placeholder': 'Link to music'
                }
            ),

        }


class CreatePhotoForm(PhotoBaseForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['workout'].queryset = user.workout_set.all()


class EditPhotoForm(PhotoBaseForm):
    class Meta:
        model = Photo
        exclude = ('user', 'image', 'date_of_publication',)

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['workout'].queryset = user.workout_set.all()


class DeletePhotoForm(FieldsMixin, PhotoBaseForm):
    disabled_fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        user = kwargs['instance'].user
        self.fields['workout'].queryset = user.workout_set.all()
        self._disable_field()

    def save(self, commit=True):
        if commit:
            LikePhoto.objects.filter(photo_id=self.instance.pk).delete()
            CommentPhoto.objects.filter(photo_id=self.instance.pk).delete()
            self.instance.delete()

        return self.instance

    class Meta:
        model = Photo
        exclude = ('user', 'image', 'date_of_publication',)

fitness_world/photos/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from fitness_world import settings
from fitness_world.common.forms import CommentCreateForm
from fitness_world.common.views import page_not_found
from fitness_world.core.core_utils import user_permissions
from fitness_world.core.photo_utils import photo_likes_count, photo_is_liked_by_user
from fitness_world.photos.forms import CreatePhotoForm, EditPhotoForm, DeletePhotoForm
from fitness_world.photos.models import Photo

UserModel = get_user_model()


class CreatePhotoView(LoginRequiredMixin, generic.CreateView):
    form_class = CreatePhotoForm
    template_name = 'photos/photo-add-page.html'
    success_url = reverse_lazy('index')

    def get_form_kwargs(self):
        result = super().get_form_kwargs()
        result['user'] = self.request.user

        return result

    def form_valid(self, form):
        photo = form.save(commit=False)
        photo.user = self.request.user
        photo.save()
        form.save_m2m()

        return super().form_valid(form)


class DetailsPhotoView(LoginRequiredMixin, generic.DetailView):
    template_name = 'photos/photo-details-page.html'
    model = Photo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        photo_likes_count(self.object)
        photo_is_liked_by_user(self.request, self.object)

        context['is_owner'] = self.request.user == self.object.user
        context['comment_form'] = CommentCreateForm()

        return context


class EditPhotoView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    template_name = 'photos/photo-edit-page.html'
    form_class = EditPhotoForm
    model = Photo

    def test_func(self):
        try:
            photo = Photo.objects.get(pk=self.kwargs.get('pk'))
            user_pk = photo.user.pk
            owner = UserModel.objects.filter(pk=user_pk).get()
            return user_permissions(self.request, owner)
        except Photo.DoesNotExist:
            page_not_found(self.request)

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return redirect(settings.LOGIN_URL)

        return page_not_found(self.request)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        kwargs['user'] = self.request.user

        return kwargs

    def get_success_url(self):
        return reverse_lazy('details photo', kwargs={
            'pk': self.object.pk
        })


@login_required
def delete_photo(request, pk):
    photo = Photo.objects.filter(pk=pk).get()

    if not user_permissions(request, photo.user):
        return page_not_found(request)

    if request.method == 'GET':
        form = DeletePhotoForm(instance=photo)
    else:
        form = DeletePhotoForm(request.POST, instance=photo)

        if form.is_valid():
            form.save()
            return redirect('index')

    context = {
        'form': form,
        'pk': pk,
    }

    return render(request, 'photos/photo-delete-page.html', context)

templates/photos/photo-add-page.html
{% extends 'base/base.html' %}

{% block content %}

<main>
    <div class="edit-delete edit-photo">
        <h2>Add Photo</h2>
        <form method="post" action="{% url 'create photo' %}" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button class="add-btn" type="submit">Add Photo</button>
        </form>
    </div>
</main>

{% endblock content %}

templates/photos/photo-delete-page.html
{% extends 'base/base.html' %}

{% block content %}


<main>
    <div class="edit-delete edit-photo">
        <h2>Delete Photo</h2>


        <form method="post" action="{% url 'delete photo' pk=pk %}" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button class="edit-btn" type="submit">Delete Photo</button>
        </form>


    </div>


</main>


{% endblock content %}

templates/photos/photo-details-page.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    <main>
        <div class="container">
            <div class="col-9">

                <div class="card">
                    <div class="top">

                        <div class="userDetails">

                            <a href="{% url 'details user' pk=object.user.pk %}">
                                <div class="profilepic">
                                    <div class="profile_img">
                                        <div class="image">
                                            {% if object.user.profile_picture %}
                                                <img src='{{ object.user.profile_picture }}' alt="img8">
                                            {% else %}
                                                <img src='{% static 'images/person.png' %}' alt="img8">
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </a>
                            <h3>

                                <a href="{% url 'details user' pk=object.user.pk %}">
                                    {% if object.user.first_name and object.user.last_name %}
                                        {{ object.user.get_full_name }}
                                    {% else %}
                                        {{ object.user.username }}
                                    {% endif %}
                                </a>
                                <br>

                                {% if object.location %}
                                    <span>{{ object.location }}</span>
                                {% endif %}

                                {% if is_owner or request.user.is_superuser %}
                                    <div class="edit-delete-btns">

                                        <a href="{% url 'edit photo' pk=object.pk %}">
                                            <img class="edit-img" src="{% static 'images/edit-pen-icon-6.jpg' %}"
                                                 alt="edit button">
                                        </a>

                                        <a href="{% url 'delete photo' pk=object.pk %}">
                                            <img class="bin-img" src="{% static 'images/icon-remove-22.jpg' %}"
                                                 alt="bin button">
                                        </a>
                                    </div>
                                {% endif %}

                            </h3>
                        </div>

                    </div>

                    <div class="imgBx" id="place the id of the photo here">
                        <img src="/media/{{ object.image }}" alt="post" class="cover">
                    </div>

                    <div class="bottom">

                        <div class="actionBtns">
                            <div class="left">

                                <span class="heart">

									<a href="{% url 'like photo' pk=object.pk %}">

										{% if object.liked_by_user %}
                                            <svg style="color: red"
                                                 xmlns="http://www.w3.org/2000/svg"
                                                 width="24"
                                                 height="24"
                                                 fill="currentColor"
                                                 class="bi bi-heart-fill"
                                                 viewBox="0 0 16 16">
                                            <path fill-rule="evenodd"
                                                  d="M8 1.314C12.438-3.248 23.534 4.735
                                                  8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                                  fill="red">
                                            </path>
                                        </svg>

                                        {% else %}
                                            <svg aria-label="Like"
                                                 color="#262626"
                                                 fill="#262626"
                                                 height="24"
                                                 role="img"
                                                 viewBox="0 0 48 48"
                                                 width="24">
                                        <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                                    11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                                    41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                                    11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                                    1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                                    1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                                    1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                                    0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                                    1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                                    1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                                    7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                                    48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                        </path>
                                        </svg>
                                        {% endif %}
								    </a>
                            </span>
                                <a href="{% url 'share photo' pk=object.pk %}">
                                    <svg aria-label="Share Post" class="_8-yf5 " color="#262626" fill="#262626"
                                         height="24" role="img" viewBox="0 0 48 48" width="24">
                                        <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3
										3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6
										1 1.2 1.1h.2c.5 0 1-.3
										1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2
										6.1h35.5L18 18.7 5.2 6.1zm18.7
										33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
                                        </path>
                                    </svg>
                                </a>
                            </div>
                        </div>

                        <p class="likes">{{ object.likes }} likes</p>

                        <p class="pet-details">{{ object.caption }}</p>

                        {% for workout in object.workout.all %}
                            <a href="{% url 'details workout' username=object.user.username slug=workout.slug %}">
                                <p class="message">
                                    <b>{{ workout.name }}</b>
                                </p>
                            </a>
                        {% endfor %}

                        <h5 class="postTime">{{ object.date_of_publication }}</h5>

                        {% for comment in object.commentphoto_set.all %}
                            <div class="comments">
                                <div class="top">
                                    <div class="userDetails">
                                        <a href="{% url 'details user' pk=comment.user.pk %}">
                                            <div class="comment-data">
                                                <div class="profilepic">
                                                    <div class="profile_img">
                                                        <div class="image">
                                                            {% if comment.user.profile_picture %}
                                                                <img src="{{ comment.user.profile_picture }}"
                                                                     alt="img8">
                                                            {% else %}
                                                                <img src="{% static 'images/person.png' %}" alt="img8">
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                                <p>
                                                    <a style="font-weight: bold"
                                                       href="{% url 'details user' pk=comment.user.pk %}">
                                                        {% if comment.user.first_name and comment.user.last_name %}
                                                            {{ comment.user.get_full_name }}
                                                        {% else %}
                                                            {{ comment.user.username }}
                                                        {% endif %}
                                                    </a>
                                                    {{ comment.text }}
                                                </p>
                                            </div>
                                            <span>{{ comment.publication_date }}</span></div>
                                </div>
                            </div>

                            {% if user == comment.user or request.user.is_superuser %}
                                <div style="text-align: right;">
                                    <ul class="edit-delete-comment">
                                        <a href="{% url 'edit comment' pk=comment.pk %}">
                                            <img style="width: 17px; height: 17px"
                                                 src="{% static 'images/edit-pen-icon-6.jpg' %}"
                                                 alt="edit button">
                                        </a>
                                        <a href="{% url 'delete comment' pk=comment.pk %}">
                                            <img style="width: 17px; height: 17px"
                                                 src="{% static 'images/icon-remove-22.jpg' %}"
                                                 alt="bin button">
                                        </a>
                                    </ul>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>

                    <div class="addComments">
                        <div class="reaction">
                            <h3>
                                <i class="far fa-smile"></i>
                            </h3>
                        </div>
                        <form method="post" action="{% url 'comment photo' pk=photo.pk %}">
                            {{ comment_form }}
                            {% csrf_token %}
                            <button type="submit">Post</button>
                        </form>

                    </div>

                </div>

            </div>
        </div>

    </main>
{% endblock content %}

templates/photos/photo-edit-page.html
{% extends 'base/base.html' %}

{% block content %}

<main>

    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <form method="post" action="{% url 'edit photo' pk=object.pk %}" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <button class="edit-btn" type="submit">Edit Photo</button>
        </form>

    </div>

</main>

{% endblock content %}